# -----------------------------------------------------------------
# Upload NORMAL modpack files to GitHub Releases
# Requirements: GitHub CLI -> https://cli.github.com/
#               Run first:   gh auth login
# -----------------------------------------------------------------

$OWNER = "DropsIZI"
$REPO  = "cobbleversemmo-modpack"
$TAG   = "v1.5-normal"

# Create release if it doesn't exist yet (skips silently if already there)
gh release create $TAG --title "CobbleverseMMO NORMAL v1.5-normal" --notes "Modpack files auto-downloaded by the launcher." --repo "$OWNER/$REPO" 2>$null

# --- mods/ (174 files [.disabled|.jar]) ---
Write-Host 'Uploading mods/ (174 files) ...'
$uploads = @(
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\accessories-fabric-1.1.0-beta.53+1.21.1.jar"; N="accessories-fabric-1.1.0-beta.53+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\accessories_compat_layer-fabric-0.1.12+1.21.1.jar"; N="accessories_compat_layer-fabric-0.1.12+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\advancementdisable-fabric-1.0.1+1.21.jar"; N="advancementdisable-fabric-1.0.1+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\AdvancementPlaques-1.21.1-fabric-1.6.8.jar"; N="AdvancementPlaques-1.21.1-fabric-1.6.8.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\architectury-13.0.8-fabric.jar"; N="architectury-13.0.8-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\athena-fabric-1.21.1-4.0.6.jar"; N="athena-fabric-1.21.1-4.0.6.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\atmosfera-2.6.0+mc1.21.1.jar"; N="atmosfera-2.6.0+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\BadOptimizations-2.4.1-1.21.1.jar"; N="BadOptimizations-2.4.1-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\badpackets-fabric-0.8.2.jar"; N="badpackets-fabric-0.8.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\balm-fabric-1.21.1-21.0.58.jar"; N="balm-fabric-1.21.1-21.0.58.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\beautify-2.0.0+1.21.1.jar"; N="beautify-2.0.0+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\betterbeds-fabric-1.4.0.jar"; N="betterbeds-fabric-1.4.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\BetterF1-Fabric-1.1+1.21.7.jar"; N="BetterF1-Fabric-1.1+1.21.7.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\BetterF3-11.0.3-Fabric-1.21.1.jar"; N="BetterF3-11.0.3-Fabric-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\BetterThirdPerson-Fabric-1.21-1.9.0.jar"; N="BetterThirdPerson-Fabric-1.21-1.9.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\biomereplacer-2.1-hippo-fabric.jar"; N="biomereplacer-2.1-hippo-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\brb-1.10.0-rc5+1.21.jar"; N="brb-1.10.0-rc5+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\c2me-fabric-mc1.21.1-0.3.0+alpha.0.362.jar"; N="c2me-fabric-mc1.21.1-0.3.0+alpha.0.362.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\capturexp-fabric-1.7.3-1.3.0.jar"; N="capturexp-fabric-1.7.3-1.3.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Carved Wood-fabric-1.21.1-1.9.5.jar"; N="Carved Wood-fabric-1.21.1-1.9.5.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\catchindicator-fabric-1.6.2.jar"; N="catchindicator-fabric-1.6.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\catchrate-display-fabric-2.8.22.jar"; N="catchrate-display-fabric-2.8.22.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\chat_heads-0.15.1-fabric-1.21.jar"; N="chat_heads-0.15.1-fabric-1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\chipped-fabric-1.21.1-4.0.2.jar"; N="chipped-fabric-1.21.1-4.0.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cloth-config-15.0.140-fabric.jar"; N="cloth-config-15.0.140-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblecuisine-2.0.1-1.7.rc1.jar"; N="cobblecuisine-2.0.1-1.7.rc1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobbledgacha-fabric-1.21.1-3.0.3.jar"; N="cobbledgacha-fabric-1.21.1-3.0.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\CobbleDollars-fabric-2.0.0+Beta-5.1+1.21.1.jar"; N="CobbleDollars-fabric-2.0.0+Beta-5.1+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\CobbleFurnies-fabric-1.1.jar"; N="CobbleFurnies-fabric-1.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon-additions-4.3.0.jar"; N="cobblemon-additions-4.3.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon-armors-1.6.0+1.7.3.jar"; N="cobblemon-armors-1.6.0+1.7.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon-battle-extras-fabric-1.13.45.jar"; N="cobblemon-battle-extras-fabric-1.13.45.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon-battle-positions-1.1.3.jar"; N="cobblemon-battle-positions-1.1.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Cobblemon-fabric-1.7.3+1.21.1.jar"; N="Cobblemon-fabric-1.7.3+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon-trainer-battle-1.11.11+1.7.3.jar"; N="cobblemon-trainer-battle-1.11.11+1.7.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon_party_extras-fabric-1.8.15.jar"; N="cobblemon_party_extras-fabric-1.8.15.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemon_ranked-v1.4.2.jar"; N="cobblemon_ranked-v1.4.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemonarmory-1.5.1-fabric-1.21.1.jar"; N="cobblemonarmory-1.5.1-fabric-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemondungeon-1.2.jar"; N="cobblemondungeon-1.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemonintegrations-fabric-1.21.1-1.1.6.jar"; N="cobblemonintegrations-fabric-1.21.1-1.1.6.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblemonraiddens-fabric-0.11.0+1.21.1.jar"; N="cobblemonraiddens-fabric-0.11.0+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\cobblenav-fabric-2.3.3.jar"; N="cobblenav-fabric-2.3.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\CobblePass-CobbleverseMMO.jar"; N="CobblePass-CobbleverseMMO.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\CobbleverseBadges-1.3.jar"; N="CobbleverseBadges-1.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Cobbreeding-fabric-2.2.1.jar"; N="Cobbreeding-fabric-2.2.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\comforts-fabric-9.0.5+1.21.1.jar"; N="comforts-fabric-9.0.5+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\continuity-3.0.0+1.21.jar"; N="continuity-3.0.0+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Controlling-fabric-1.21.1-19.0.5.jar"; N="Controlling-fabric-1.21.1-19.0.5.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Corgilib-Fabric-1.21.1-5.0.0.9.jar"; N="Corgilib-Fabric-1.21.1-5.0.0.9.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\counter-fabric-1.7.3-1.9.0.jar"; N="counter-fabric-1.7.3-1.9.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\customsplashscreen-2.2.0.jar"; N="customsplashscreen-2.2.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Data_Anchor-fabric-1.21.1-2.0.0.14.jar"; N="Data_Anchor-fabric-1.21.1-2.0.0.14.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Debugify-1.21.1+1.0.jar"; N="Debugify-1.21.1+1.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\defaultoptions-fabric-1.21.1-21.1.5.jar"; N="defaultoptions-fabric-1.21.1-21.1.5.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\dynamicsurroundings-fabric-1.21.1-0.4.2.jar"; N="dynamicsurroundings-fabric-1.21.1-0.4.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\easy_npc-fabric-1.21.1-6.15.0.jar"; N="easy_npc-fabric-1.21.1-6.15.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\easy_npc_bundle-fabric-1.21.1-6.15.0.jar"; N="easy_npc_bundle-fabric-1.21.1-6.15.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\easy_npc_config_ui-fabric-1.21.1-6.15.0.jar"; N="easy_npc_config_ui-fabric-1.21.1-6.15.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ecologics-fabric-1.21.1-2.3.6.jar"; N="ecologics-fabric-1.21.1-2.3.6.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Enhanced-Celestials-Fabric-1.21.1-6.0.2.5.jar"; N="Enhanced-Celestials-Fabric-1.21.1-6.0.2.5.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\entity_model_features-3.2.4-1.21-fabric.jar"; N="entity_model_features-3.2.4-1.21-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\entity_texture_features_1.21-fabric-7.1.jar"; N="entity_texture_features_1.21-fabric-7.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\entityculling-fabric-1.10.2-mc1.21.1.jar"; N="entityculling-fabric-1.10.2-mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\EuphoriaPatcher-1.9.0-r5.8-fabric.jar"; N="EuphoriaPatcher-1.9.0-r5.8-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\fabric-api-0.116.12+1.21.1.jar"; N="fabric-api-0.116.12+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\fabric-language-kotlin-1.13.11+kotlin.2.3.21.jar"; N="fabric-language-kotlin-1.13.11+kotlin.2.3.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\fancymenu_fabric_3.9.1_MC_1.21.1.jar"; N="fancymenu_fabric_3.9.1_MC_1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ferritecore-7.0.3-fabric.jar"; N="ferritecore-7.0.3-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\fightorflight-fabric-0.10.7.jar"; N="fightorflight-fabric-0.10.7.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ForgeConfigAPIPort-v21.1.6-1.21.1-Fabric.jar"; N="ForgeConfigAPIPort-v21.1.6-1.21.1-Fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\forgivingvoid-fabric-1.21.1-21.1.7.jar"; N="forgivingvoid-fabric-1.21.1-21.1.7.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\fusion-1.2.12-fabric-mc1.21.jar"; N="fusion-1.2.12-fabric-mc1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\fzzy_config-0.7.6+1.21.jar"; N="fzzy_config-0.7.6+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\geckolib-fabric-1.21.1-4.8.4.jar"; N="geckolib-fabric-1.21.1-4.8.4.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\globalpacks-fabric-1.21.1-21.0.6.jar"; N="globalpacks-fabric-1.21.1-21.0.6.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\GooeyLibs-Fabric-3.1.1-1.21.x.jar"; N="GooeyLibs-Fabric-3.1.1-1.21.x.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\handcrafted-fabric-1.21.1-4.0.3.jar"; N="handcrafted-fabric-1.21.1-4.0.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\highlight-fabric-1.21-3.0.0.jar"; N="highlight-fabric-1.21-3.0.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\huge-structure-blocks-fabric-1.1.6.jar"; N="huge-structure-blocks-fabric-1.1.6.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Iceberg-1.21.1-fabric-1.3.2.jar"; N="Iceberg-1.21.1-fabric-1.3.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ImmediatelyFast-Fabric-1.6.10+1.21.1.jar"; N="ImmediatelyFast-Fabric-1.6.10+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ImmersiveThunder-1.21.1+1.2.2.jar"; N="ImmersiveThunder-1.21.1+1.2.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Impactor-Fabric-5.3.5+1.21.1.jar"; N="Impactor-Fabric-5.3.5+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\infinite-music-0.4.6.jar"; N="infinite-music-0.4.6.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\interactic-0.2.3+1.21.jar"; N="interactic-0.2.3+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\iris-fabric-1.8.8+mc1.21.1.jar"; N="iris-fabric-1.8.8+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\konkrete_fabric_1.9.9_MC_1.21.jar"; N="konkrete_fabric_1.9.9_MC_1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\krypton-0.2.8.jar"; N="krypton-0.2.8.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\LegendaryMonuments-Cobbleverse.jar"; N="LegendaryMonuments-Cobbleverse.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\lenientdeath-1.2.5+1.21.1.jar"; N="lenientdeath-1.2.5+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\libjf-3.17.5.jar"; N="libjf-3.17.5.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\lithium-fabric-0.15.3+mc1.21.1.jar"; N="lithium-fabric-0.15.3+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Lookin-Sharp-fabric-1.0.4.jar"; N="Lookin-Sharp-fabric-1.0.4.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Luckys-Cozyhome-Refurnished-1.1.20.jar"; N="Luckys-Cozyhome-Refurnished-1.1.20.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\LumyMon-0.6.5.jar"; N="LumyMon-0.6.5.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\LumyREI-1.1.3.jar"; N="LumyREI-1.1.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\malilib-fabric-1.21-0.21.10.jar"; N="malilib-fabric-1.21-0.21.10.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\mega_showdown-fabric-1.8.4+1.7.3+1.21.1.jar"; N="mega_showdown-fabric-1.8.4+1.7.3+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\melody_fabric_1.0.10_MC_1.21.jar"; N="melody_fabric_1.0.10_MC_1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\midnightlib-1.7.5-fabric+1.21.1.jar"; N="midnightlib-1.7.5-fabric+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\moar-concrete-1.3.1.jar"; N="moar-concrete-1.3.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\MobsBeGone-0.0.7.jar"; N="MobsBeGone-0.0.7.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\modernfix-fabric-5.25.1+mc1.21.1.jar"; N="modernfix-fabric-5.25.1+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\modmenu-11.0.4.jar"; N="modmenu-11.0.4.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\MoreCobblemonTweaks-fabric-1.3.3.jar"; N="MoreCobblemonTweaks-fabric-1.3.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\moreculling-fabric-1.21.1-1.0.7.jar"; N="moreculling-fabric-1.21.1-1.0.7.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\MoreTotems-fabric-1.21-2.20.3.jar"; N="MoreTotems-fabric-1.21-2.20.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\MouseTweaks-fabric-mc1.21-2.26.jar"; N="MouseTweaks-fabric-mc1.21-2.26.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\mru-1.0.19+LTS+1.21.1+fabric.jar"; N="mru-1.0.19+LTS+1.21.1+fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\musicnotification-fabric-3.0.0+mc1.21.1.jar"; N="musicnotification-fabric-3.0.0+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\MyTotemDoll-2.3.3+1.21.1.jar"; N="MyTotemDoll-2.3.3+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Necronomicon-Fabric-1.6.0+1.21.jar"; N="Necronomicon-Fabric-1.6.0+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\nethermap-4.0.0-1.21.1.jar"; N="nethermap-4.0.0-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\netherportalfix-fabric-1.21.1-21.1.3.jar"; N="netherportalfix-fabric-1.21.1-21.1.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\notenoughanimations-fabric-1.12.3-mc1.21.1.jar"; N="notenoughanimations-fabric-1.12.3-mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\notenoughcrashes-fabric-4.4.9+1.21.1.jar"; N="notenoughcrashes-fabric-4.4.9+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\OELib-fabric-1.21.1-0.2.3.jar"; N="OELib-fabric-1.21.1-0.2.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Only Bottle Caps-1.3.0.jar"; N="Only Bottle Caps-1.3.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\owo-lib-0.12.15.4+1.21.jar"; N="owo-lib-0.12.15.4+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\packetfixer-3.3.1-1.20.5-1.21.X-merged.jar"; N="packetfixer-3.3.1-1.20.5-1.21.X-merged.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\paginatedadvancements-2.5.1.jar"; N="paginatedadvancements-2.5.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\particle_core-0.3.3+1.21.jar"; N="particle_core-0.3.3+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\particlerain-4.0.0-beta.9+1.21.1-fabric.jar"; N="particlerain-4.0.0-beta.9+1.21.1-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\particular-1.1.2+1.21.jar"; N="particular-1.1.2+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\pastureLoot-1.0.5+1.21.1.jar"; N="pastureLoot-1.0.5+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Ping-Wheel-1.12.1-fabric-1.21.1.jar"; N="Ping-Wheel-1.12.1-fabric-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\placeholder-api-2.4.2+1.21.jar"; N="placeholder-api-2.4.2+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Platform-fabric-1.21.1-1.3.jar"; N="Platform-fabric-1.21.1-1.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\playerxp-fabric-1.0.9+1.21.1.jar"; N="playerxp-fabric-1.0.9+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\pokeblocks-1.5.0-1.21.1.jar"; N="pokeblocks-1.5.0-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\rctapi-fabric-1.21.1-0.15.2-beta.jar"; N="rctapi-fabric-1.21.1-0.15.2-beta.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\rctmod-fabric-1.21.1-0.18.1-beta.jar"; N="rctmod-fabric-1.21.1-0.18.1-beta.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\rechiseled-1.2.4-fabric-mc1.21.jar"; N="rechiseled-1.2.4-fabric-mc1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\reeses-sodium-options-fabric-1.8.3+mc1.21.4.jar"; N="reeses-sodium-options-fabric-1.8.3+mc1.21.4.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\repurposed_structures-7.5.20+1.21.1-fabric.jar"; N="repurposed_structures-7.5.20+1.21.1-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\resourcefullib-fabric-1.21-3.0.12.jar"; N="resourcefullib-fabric-1.21-3.0.12.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ResourcePackOverrides-v21.1.0-1.21.1-Fabric.jar"; N="ResourcePackOverrides-v21.1.0-1.21.1-Fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\respackopts-4.14.0+1.21.1.4.jar"; N="respackopts-4.14.0+1.21.1.4.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\rottencreatures-fabric-1.21.1-1.1.2.jar"; N="rottencreatures-fabric-1.21.1-1.1.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\RoughlyEnoughItems-16.0.799-fabric.jar"; N="RoughlyEnoughItems-16.0.799-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\SafePastures-1.1.1+1.21.1.jar"; N="SafePastures-1.1.1+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\ScalableLux-0.1.0.1+fabric.d0d58ab-all.jar"; N="ScalableLux-0.1.0.1+fabric.d0d58ab-all.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\Searchables-fabric-1.21.1-1.0.2.jar"; N="Searchables-fabric-1.21.1-1.0.2.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sodium-extra-fabric-0.6.0+mc1.21.1.jar"; N="sodium-extra-fabric-0.6.0+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sodium-fabric-0.6.13+mc1.21.1.jar"; N="sodium-fabric-0.6.13+mc1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sodiumoptionsapi-fabric-1.0.10-1.21.1.jar"; N="sodiumoptionsapi-fabric-1.0.10-1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sophisticatedbackpacks-1.21.1-3.23.4.3.106.jar"; N="sophisticatedbackpacks-1.21.1-3.23.4.3.106.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sophisticatedcore-1.21.1-1.2.9.21.168.jar"; N="sophisticatedcore-1.21.1-1.2.9.21.168.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sophisticatedstorage-1.21.1-1.3.7.9.139.jar"; N="sophisticatedstorage-1.21.1-1.3.7.9.139.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sound-physics-remastered-fabric-1.21.1-1.5.1.jar"; N="sound-physics-remastered-fabric-1.21.1-1.5.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\sounds-2.4.22+lts+1.21.1-fabric.jar"; N="sounds-2.4.22+lts+1.21.1-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\soundsbegone-fabric-1.5.1+mc1.21.jar"; N="soundsbegone-fabric-1.5.1+mc1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\StackDeobfuscatorFabric-1.4.3+08e71cc.jar"; N="StackDeobfuscatorFabric-1.4.3+08e71cc.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\supermartijn642configlib-1.1.8-fabric-mc1.21.jar"; N="supermartijn642configlib-1.1.8-fabric-mc1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\supermartijn642corelib-1.1.21-fabric-mc1.21.jar"; N="supermartijn642corelib-1.1.21-fabric-mc1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\tbcs-fabric-1.21.1-0.14.1-beta.jar"; N="tbcs-fabric-1.21.1-0.14.1-beta.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\TerraBlender-fabric-1.21.1-4.1.0.8.jar"; N="TerraBlender-fabric-1.21.1-4.1.0.8.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\timcore-fabric-1.7.3-1.32.0.jar"; N="timcore-fabric-1.7.3-1.32.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\tmcraft-1.4.18+1.7.3.jar"; N="tmcraft-1.4.18+1.7.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\toms_storage_fabric-1.21-2.3.0.jar"; N="toms_storage_fabric-1.21-2.3.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\tooltipfix-1.1.1-1.20.jar"; N="tooltipfix-1.1.1-1.20.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\trinkets-3.10.0.jar"; N="trinkets-3.10.0.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\VanillaBackport-fabric-1.21.1-1.1.6.3.jar"; N="VanillaBackport-fabric-1.21.1-1.1.6.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\vcinteraction-fabric-1.21.1-1.0.8.jar.disabled"; N="vcinteraction-fabric-1.21.1-1.0.8.jar.disabled" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\villagerconfig-fabric-4.5.3+1.21.1.jar"; N="villagerconfig-fabric-4.5.3+1.21.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\voicechat-fabric-1.21.1-2.6.17.jar"; N="voicechat-fabric-1.21.1-2.6.17.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\waystones-fabric-1.21.1-21.1.33.jar"; N="waystones-fabric-1.21.1-21.1.33.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\wthit-1.21.1-fabric-12.10.1.jar"; N="wthit-1.21.1-fabric-12.10.1.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\xaerominimap-fabric-1.21.1-25.3.12.jar"; N="xaerominimap-fabric-1.21.1-25.3.12.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\xaeroworldmap-fabric-1.21.1-1.40.16.jar"; N="xaeroworldmap-fabric-1.21.1-1.40.16.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\yet_another_config_lib_v3-3.8.2+1.21.1-fabric.jar"; N="yet_another_config_lib_v3-3.8.2+1.21.1-fabric.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\zamega-fabric-1.7.3.jar"; N="zamega-fabric-1.7.3.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\zfastnoise-1.0.11+1.21.jar"; N="zfastnoise-1.0.11+1.21.jar" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\mods\zoomify-2.15.2+1.21.1.jar"; N="zoomify-2.15.2+1.21.1.jar" }
)
foreach ($u in $uploads) {
    Write-Host "  $($u.N)"
    gh release upload $TAG $u.P --clobber --repo "$OWNER/$REPO"
}

# --- datapacks/ (11 files [.zip]) ---
Write-Host 'Uploading datapacks/ (11 files) ...'
$uploads = @(
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\ATM x MSD [v3.5.0].zip"; N="ATM x MSD [v3.5.0].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\COBBLEVERSE - No Ender Dragon.zip"; N="COBBLEVERSE - No Ender Dragon.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\COBBLEVERSE - No Hunger.zip"; N="COBBLEVERSE - No Hunger.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\COBBLEVERSE-DP-v29.zip"; N="COBBLEVERSE-DP-v29.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\COBBLEVERSE-Loot-DP-v11.zip"; N="COBBLEVERSE-Loot-DP-v11.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\COBBLEVERSE-RCT-DP-v19.zip"; N="COBBLEVERSE-RCT-DP-v19.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\extra\COBBLEVERSE-Hoenn-DP.zip"; N="COBBLEVERSE-Hoenn-DP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\extra\COBBLEVERSE-Johto-DP.zip"; N="COBBLEVERSE-Johto-DP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\extra\COBBLEVERSE-Sinnoh-DP.zip"; N="COBBLEVERSE-Sinnoh-DP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\extra\Terralith-DP.zip"; N="Terralith-DP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\datapacks\PokeCenterPCs-DP.zip"; N="PokeCenterPCs-DP.zip" }
)
foreach ($u in $uploads) {
    Write-Host "  $($u.N)"
    gh release upload $TAG $u.P --clobber --repo "$OWNER/$REPO"
}

# --- resourcepacks/ (51 files [.rpo|.zip]) ---
Write-Host 'Uploading resourcepacks/ (51 files) ...'
$uploads = @(
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\ATMxMSD RP.zip"; N="ATMxMSD RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Canon PC Wallpapers.zip"; N="Canon PC Wallpapers.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\CavsCobbleMons RP.zip"; N="CavsCobbleMons RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Classic Grass.zip"; N="Classic Grass.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Cobblemon Interface Modded.zip"; N="Cobblemon Interface Modded.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Cobblemon Interface Modded.zip.rpo"; N="Cobblemon Interface Modded.zip.rpo" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Cobblemon Interface.zip"; N="Cobblemon Interface.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Cobblemon Interface.zip.rpo"; N="Cobblemon Interface.zip.rpo" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\CobbleMotion RP.zip"; N="CobbleMotion RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\CobbleMotion_v1.5.zip"; N="CobbleMotion_v1.5.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\COBBLEVERSE RCTmod RP.zip"; N="COBBLEVERSE RCTmod RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\COBBLEVERSE RP.zip"; N="COBBLEVERSE RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\COBBLEVERSE Soundtrack.zip"; N="COBBLEVERSE Soundtrack.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Cobbleverse-Rankicons-RP.zip"; N="Cobbleverse-Rankicons-RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Comforts Modernized.zip"; N="Comforts Modernized.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\E19 Cobblemon Minimap Icons.zip"; N="E19 Cobblemon Minimap Icons.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\EeveelutionsReimagined RP.zip"; N="EeveelutionsReimagined RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Emissive Cobblemon Ores.zip"; N="Emissive Cobblemon Ores.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Fresh Animations.zip"; N="Fresh Animations.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Fresh Icons.zip"; N="Fresh Icons.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Fresh Moves.zip"; N="Fresh Moves.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\FullyHisuianStarters RP.zip"; N="FullyHisuianStarters RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\GlitchDex RP.zip"; N="GlitchDex RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\HydroReanimodel RP.zip"; N="HydroReanimodel RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\JigglyRadio.zip"; N="JigglyRadio.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\LackingMons RP.zip"; N="LackingMons RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Low Fire.zip"; N="Low Fire.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\MelloMons RP.zip"; N="MelloMons RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\MissingMons RP.zip"; N="MissingMons RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\MundialMons RP.zip"; N="MundialMons RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\MysticMons RP.zip"; N="MysticMons RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\OJsAnimations RP.zip"; N="OJsAnimations RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Original Pokemon Battle Music.zip"; N="Original Pokemon Battle Music.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\PlanetaCobblemon RP.zip"; N="PlanetaCobblemon RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\PokeDiscs.zip"; N="PokeDiscs.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\Pokemans RP.zip"; N="Pokemans RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\PokeRods3D.zip"; N="PokeRods3D.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\SailorMon-ResourcePack.zip"; N="SailorMon-ResourcePack.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\TDmon RP.zip"; N="TDmon RP.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [CavsCobbleMons - Credits Only].zip"; N="z DO NOT ENABLE z [CavsCobbleMons - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [E19 Minimap Icons - Credits Only].zip"; N="z DO NOT ENABLE z [E19 Minimap Icons - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [GlitchDex - Credits Only].zip"; N="z DO NOT ENABLE z [GlitchDex - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [Hydro Reanimodel - Credits Only].zip"; N="z DO NOT ENABLE z [Hydro Reanimodel - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [LackingMons - Credits Only].zip"; N="z DO NOT ENABLE z [LackingMons - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [MissingMons - Credits Only].zip"; N="z DO NOT ENABLE z [MissingMons - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [MundialMons - Credits Only].zip"; N="z DO NOT ENABLE z [MundialMons - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [MysticMons - Credits Only].zip"; N="z DO NOT ENABLE z [MysticMons - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [PlanetaCobblemon - Credits Only].zip"; N="z DO NOT ENABLE z [PlanetaCobblemon - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [Pokemans - Credits Only].zip"; N="z DO NOT ENABLE z [Pokemans - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [TDmon - Credits Only].zip"; N="z DO NOT ENABLE z [TDmon - Credits Only].zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\resourcepacks\z DO NOT ENABLE z [Terralith - Credits Only].zip"; N="z DO NOT ENABLE z [Terralith - Credits Only].zip" }
)
foreach ($u in $uploads) {
    Write-Host "  $($u.N)"
    gh release upload $TAG $u.P --clobber --repo "$OWNER/$REPO"
}

# --- shaderpacks/ (9 files [.txt|.zip]) ---
Write-Host 'Uploading shaderpacks/ (9 files) ...'
$uploads = @(
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\shaderpacks\COBBLEVERSE - Shaders (High Quality).txt"; N="shaderpacks--COBBLEVERSE - Shaders (High Quality).txt" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\shaderpacks\COBBLEVERSE - Shaders.txt"; N="shaderpacks--COBBLEVERSE - Shaders.txt" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\shaderpacks\ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6.txt"; N="shaderpacks--ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6.txt" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\shaderpacks\ComplementaryUnbound_r5.7.1.zip"; N="shaderpacks--ComplementaryUnbound_r5.7.1.zip" },
    @{ P="C:\Users\Acer\AppData\Roaming\ModrinthApp\profiles\COBBLEVERSEMMO 1.5\shaderpacks\MakeUp-UltraFast-9.5a.zip"; N="shaderpacks--MakeUp-UltraFast-9.5a.zip" },
    @{ P="C:\Users\Acer\Documents\Launcher CobbleverseMMO\_staging\normal\_0EuphoriaPatches_ErrorShader.zip"; N="shaderpacks--_0EuphoriaPatches_ErrorShader.zip" },
    @{ P="C:\Users\Acer\Documents\Launcher CobbleverseMMO\_staging\normal\COBBLEVERSE - Shaders.zip"; N="shaderpacks--COBBLEVERSE - Shaders.zip" },
    @{ P="C:\Users\Acer\Documents\Launcher CobbleverseMMO\_staging\normal\COBBLEVERSE - Shaders (High Quality).zip"; N="shaderpacks--COBBLEVERSE - Shaders (High Quality).zip" },
    @{ P="C:\Users\Acer\Documents\Launcher CobbleverseMMO\_staging\normal\ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6.zip"; N="shaderpacks--ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6.zip" }
)
foreach ($u in $uploads) {
    Write-Host "  $($u.N)"
    gh release upload $TAG $u.P --clobber --repo "$OWNER/$REPO"
}

Write-Host ''
Write-Host 'Done!'
Write-Host "  https://github.com/$OWNER/$REPO/releases/tag/$TAG"